apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ironlatch-ingress
spec:
  podSelector:
    matchLabels:
      app: ironlatch
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 8000
