{
 "title": "IronLatch Operations Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval0",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "IronLatch Total API Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(http_requests_total)", "legendFormat": "__auto" },
    {
     "expr": "sum by (handler) (rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IronLatch Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (handler) (irate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IronLatch Error Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_requests_total{status=~\"4xx|5xx\"}[5m])) / sum(rate(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IronLatch P95 Response Latency",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, handler) (\r\n    rate(http_request_duration_seconds_bucket[5m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IronLatch Available Replicas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{\r\n  namespace=\"default\",\r\n  deployment=\"ironlatch\"\r\n}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IronLatch CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\nsum(\r\n  rate(\r\n    container_cpu_usage_seconds_total{\r\n      namespace=\"default\",\r\n      pod=~\"ironlatch-.*\",\r\n      container=\"ironlatch\"\r\n    }[5m]\r\n  )\r\n)\r\n/\r\nsum(\r\n  kube_pod_container_resource_limits{\r\n    namespace=\"default\",\r\n    pod=~\"ironlatch-.*\",\r\n    container=\"ironlatch\",\r\n    resource=\"cpu\",\r\n    unit=\"core\"\r\n  }\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IronLatch Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\nsum(\r\n  container_memory_working_set_bytes{\r\n    namespace=\"default\",\r\n    pod=~\"ironlatch-.*\",\r\n    container=\"ironlatch\"\r\n  }\r\n)\r\n/\r\nsum(\r\n  kube_pod_container_resource_limits{\r\n    namespace=\"default\",\r\n    pod=~\"ironlatch-.*\",\r\n    container=\"ironlatch\",\r\n    resource=\"memory\",\r\n    unit=\"byte\"\r\n  }\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}